sudo: required
# dist: trusty # see https://docs.travis-ci.com/user/ci-environment

language: c

services:
  - docker

env:
  - BAGTAINER_ID="0002"
#  - BAGTAINER_ID="0003"

install:
  - docker build -t bagtainers/$BAGTAINER_ID $BAGTAINER_ID/data/container/.

before_script:
  - printenv
  - mkdir -p ~/o2r/run
#  - useradd docker
  - chown docker:docker ~/o2r/run
  - id
  - ls -l ~/o2r
  - ls -l ~/o2r/run

script:
- docker run --user docker -v $(pwd)/$BAGTAINER_ID:/bag:ro -v ~/o2r/run:/o2r_run:rw bagtainers/$BAGTAINER_ID

notifications:
  email:
    - daniel.nuest@uni-muenster.de
